version: '3.3'

services:
  db:
    image: mongo
    ports:
    - 27017:27017

  backend:
    build: backend
    command: sh -c './wait-for db:27017 -- npm run dev'
    environment:
      DATABASE_URL: mongodb://db:27017/mugu
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8090:8090
    depends_on:
      - db

  frontend:
    build: frontend
    environment:
      - ENDPOINT=${ENDPOINT:-http://localhost:8090/api}
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - 8080:8080
